#!/bin/sh
# W0-03: Start local integration stack (Linux/WSL — PowerShell is authoritative Windows path).
# Generates .env.local with random passwords on first run.
# All services bind to 127.0.0.1 only.
# OpenBao bootstrap runs via docker exec (no host bao required).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_LOCAL="$ROOT_DIR/.env.local"

cd "$ROOT_DIR"

# Generate .env.local on first run
if [ ! -f "$ENV_LOCAL" ]; then
  echo "[local-stack] Generating .env.local with random secrets..."
  PG_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 20)
  MINIO_ACCESS=$(openssl rand -hex 12)
  MINIO_SECRET=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
  OPENBAO_TOKEN=$(openssl rand -hex 16)
  cat > "$ENV_LOCAL" <<EOF
# Generated by local-stack-up.sh — do not commit
LOCAL_PG_PASSWORD=${PG_PASS}
LOCAL_MINIO_ACCESS_KEY=${MINIO_ACCESS}
LOCAL_MINIO_SECRET_KEY=${MINIO_SECRET}
LOCAL_OPENBAO_ROOT_TOKEN=${OPENBAO_TOKEN}
EOF
  chmod 600 "$ENV_LOCAL"
  echo "[local-stack] .env.local created (random secrets)."
fi

# Start services
echo "[local-stack] Starting services..."
docker compose -f compose.local.yml --env-file .env.local up -d

# Wait for all services to be healthy
echo "[local-stack] Waiting for services to be healthy..."
TIMEOUT=120; ELAPSED=0
while [ $ELAPSED -lt $TIMEOUT ]; do
  HEALTHY=$(docker compose -f compose.local.yml --env-file .env.local ps --format json 2>/dev/null | grep -o '"healthy"' | wc -l)
  if [ "$HEALTHY" -ge 2 ]; then break; fi
  sleep 3; ELAPSED=$((ELAPSED + 3))
done

# Bootstrap OpenBao via docker exec (no host bao required)
echo "[local-stack] Bootstrapping OpenBao..."
ROOT_TOKEN=$(grep "LOCAL_OPENBAO_ROOT_TOKEN" "$ENV_LOCAL" | cut -d= -f2)
docker exec -e BAO_ADDR=http://127.0.0.1:8200 markflow-local-openbao sh -c "
bao login '$ROOT_TOKEN' >/dev/null 2>&1
echo '[openbao-init] Authenticated.'
bao secrets enable -path=transit transit 2>/dev/null || echo '[openbao-init] Transit already enabled.'
bao write -f transit/keys/markflow-local 2>/dev/null || echo '[openbao-init] Key exists.'
bao policy write markflow-dev - 'path transit/encrypt/markflow-local { capabilities = [update] } path transit/decrypt/markflow-local { capabilities = [update] } path transit/keys/markflow-local { capabilities = [read] } path sys/health { capabilities = [read] }'
echo '[openbao-init] Bootstrap complete.'
" 2>&1

if [ $? -ne 0 ]; then
  echo "[local-stack] FAIL: OpenBao bootstrap failed"
  exit 1
fi

echo ""
echo "[local-stack] Services started and OpenBao bootstrapped."
echo "[local-stack] Run 'scripts/local-stack-status.sh' to verify."
echo "[local-stack] Run 'scripts/local-smoke.sh' to run smoke tests."
