#!/bin/sh
# W0-03: OpenBao local dev bootstrap.
# Uses dev mode root token (auto-generated by bao server -dev).
# STRICTLY DEV MODE — never used in Stage/Production.

set -e

BAO_ADDR="${BAO_ADDR:-http://localhost:8200}"

# Wait for OpenBao to be ready
echo "[openbao-init] Waiting for OpenBao..."
for i in $(seq 1 30); do
  if BAO_ADDR="$BAO_ADDR" bao status >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# Read dev root token from file (written by bao server -dev)
TOKEN_FILE="${BAO_DEV_ROOT_TOKEN_FILE:-/bao/data/dev-root-token}"
if [ -f "$TOKEN_FILE" ]; then
  ROOT_TOKEN=$(cat "$TOKEN_FILE")
  export BAO_TOKEN="$ROOT_TOKEN"
  echo "[openbao-init] Using dev root token from $TOKEN_FILE"
else
  echo "[openbao-init] WARNING: No root token file found at $TOKEN_FILE"
  exit 1
fi

# Enable Transit secrets engine
echo "[openbao-init] Enabling Transit engine..."
bao secrets enable -path=transit transit 2>/dev/null || true

# Create encryption key (default type: aes256-gcm96)
echo "[openbao-init] Creating markflow-local key..."
bao write -f transit/keys/markflow-local 2>/dev/null || true

# Create a dev policy with minimal permissions
echo "[openbao-init] Creating markflow-dev policy..."
bao policy write markflow-dev - <<'EOF'
path "transit/encrypt/markflow-local" {
  capabilities = ["update"]
}
path "transit/decrypt/markflow-local" {
  capabilities = ["update"]
}
path "transit/keys/markflow-local" {
  capabilities = ["read"]
}
path "sys/health" {
  capabilities = ["read"]
}
EOF

# Create a dev token with the markflow-dev policy (1 hour TTL)
echo "[openbao-init] Creating dev token..."
DEV_TOKEN=$(bao token create -policy=markflow-dev -format=json -ttl=3600 2>/dev/null | grep -o '"client_token":"[^"]*"' | cut -d'"' -f4 || true)

if [ -n "$DEV_TOKEN" ]; then
  echo "$DEV_TOKEN" > /bao/data/init-token
  chmod 600 /bao/data/init-token
  echo "[openbao-init] Dev token created and stored at /bao/data/init-token"
else
  echo "[openbao-init] WARNING: Could not create dev token"
fi

echo "[openbao-init] Bootstrap complete."
