#!/bin/sh
# W0-03: Start local integration stack (PG16, MinIO, OpenBao).
# Generates .env.local with random passwords on first run.
# All services bind to 127.0.0.1 only.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_LOCAL="$ROOT_DIR/.env.local"
ENV_EXAMPLE="$ROOT_DIR/.env.local.example"

cd "$ROOT_DIR"

# Generate .env.local on first run
if [ ! -f "$ENV_LOCAL" ]; then
  echo "[local-stack] Generating .env.local with random secrets..."
  PG_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 20)
  MINIO_ACCESS=$(openssl rand -hex 12)
  MINIO_SECRET=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
  cat > "$ENV_LOCAL" <<EOF
# Generated by local-stack-up.sh — do not commit
LOCAL_PG_PASSWORD=${PG_PASS}
LOCAL_MINIO_ACCESS_KEY=${MINIO_ACCESS}
LOCAL_MINIO_SECRET_KEY=${MINIO_SECRET}
EOF
  chmod 600 "$ENV_LOCAL"
  echo "[local-stack] .env.local created (random passwords)."
fi

# Start services
echo "[local-stack] Starting services..."
docker compose -f compose.local.yml --env-file .env.local up -d

# Wait for health
echo "[local-stack] Waiting for services to be healthy..."
docker compose -f compose.local.yml --env-file .env.local ps

echo ""
echo "[local-stack] Services started. Run 'scripts/local-stack-status.sh' to verify."
echo "[local-stack] Run 'scripts/local-smoke.sh' to run integration smoke tests."
