#!/bin/sh
# W0-03-fix: Start local integration stack (PG16, MinIO, OpenBao).
# Generates .env.local with random passwords on first run.
# All services bind to 127.0.0.1 only.
# Waits for OpenBao health, then runs bootstrap from the host.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_LOCAL="$ROOT_DIR/.env.local"

cd "$ROOT_DIR"

# Generate .env.local on first run
if [ ! -f "$ENV_LOCAL" ]; then
  echo "[local-stack] Generating .env.local with random secrets..."
  PG_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 20)
  MINIO_ACCESS=$(openssl rand -hex 12)
  MINIO_SECRET=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
  OPENBAO_TOKEN=$(openssl rand -hex 16)
  cat > "$ENV_LOCAL" <<EOF
# Generated by local-stack-up.sh — do not commit
LOCAL_PG_PASSWORD=${PG_PASS}
LOCAL_MINIO_ACCESS_KEY=${MINIO_ACCESS}
LOCAL_MINIO_SECRET_KEY=${MINIO_SECRET}
LOCAL_OPENBAO_ROOT_TOKEN=${OPENBAO_TOKEN}
EOF
  chmod 600 "$ENV_LOCAL"
  echo "[local-stack] .env.local created (random secrets)."
fi

# Start services
echo "[local-stack] Starting services..."
docker compose -f compose.local.yml --env-file .env.local up -d

# Wait for all services to be healthy
echo "[local-stack] Waiting for services to be healthy..."
TIMEOUT=120
ELAPSED=0
while [ $ELAPSED -lt $TIMEOUT ]; do
  HEALTHY=$(docker compose -f compose.local.yml --env-file .env.local ps --format json 2>/dev/null | grep -o '"healthy"' | wc -l)
  if [ "$HEALTHY" -ge 2 ]; then
    break
  fi
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done

# Run OpenBao bootstrap from the host (avoids container token-helper issues)
echo "[local-stack] Bootstrapping OpenBao..."
. "$ENV_LOCAL"
export BAO_ADDR="http://127.0.0.1:8200"
bash "$SCRIPT_DIR/local-openbao-bootstrap.sh"
INIT_EXIT=$?

if [ $INIT_EXIT -ne 0 ]; then
  echo "[local-stack] FAIL: OpenBao bootstrap failed (exit code $INIT_EXIT)"
  exit 1
fi

echo ""
echo "[local-stack] Services started and OpenBao bootstrapped."
echo "[local-stack] Run 'scripts/local-stack-status.sh' to verify."
echo "[local-stack] Run 'scripts/local-smoke.sh' to run integration smoke tests."
